### ISSUE TITLE
hapi-couchdb-account (hapi plugin) integration

### ISSUE THREAD

**Issue by tthew** [eHealthAfrica/kazana-account#45]
It would be great to refactor this module to use `hapi-couchdb-account`.

Ideally there would be a mechanism to pass this plugin directly to hapi in order to expose the core routes / functionality exposed by this module, and also support the existing routes interface in order to extend the feature set if required.

Any thoughts on clean ways to implement this?

**Comment by patriciagarcia** [comment]
cc/ @gr2m

**Comment by gr2m** [comment]
I'll look into kazana-account / hapi-couchdb-account first thing next week. I don't think we need to expose routes directly, instead kazana-account would use the hapi-couchdb-account hapi plugin internally, and we will make sure to expose all methods that are needed to kazana

**Comment by gr2m** [comment]
We want to move out the routes of hapi-couchdb-account into its own module (probably hapi-couchdb-account-api, but naming is hard™) which we then can use in kazana-account, without the current overhead of hapi-couchdb-account.

That should help already, right @tthew?

**Comment by tthew** [comment]
:+1:

**Comment by gr2m** [comment]
working on this now, I should have something by tomorrow if nothing else comes up today :)

**Comment by gr2m** [comment]
Here we go https://github.com/hoodiehq/hapi-couchdb-account-api

**Comment by patriciagarcia** [comment]
We'll we still be using `hapi-couchdb-account-api` plugin internally and exposing our own routes within `kazana-account`, or will we expose `hapi-couchdb-account-api` routes directly?

**Comment by patriciagarcia** [comment]
@gr2m, @tthew, I guess we can close this question now?

**Comment by gr2m** [comment]
good with me, we can create follow up issues for follow up questions?

**Comment by tthew** [comment]
:+1:
